captainVersion: 4
services:
    $$cap_appname:
        image: audio-transcribe
        ports:
            - 5001:5000
        volumes:
            - $$cap_appname:/app/instance
        environment:
            - WISPHER_MODEL=$$wispher_model
            - ADMIN_PASSWORD=$$admin_password
caproverOneClickApp:
    variables:
        - id: $$wispher_model
          label: Wispher Model
          defaultValue: base
          validRegex: '^[a-zA-Z]+$'
        - id: $$admin_password
          label: Admin Password
          description: Enter the admin password. Please use a string one.
          validRegex: '^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$'
          required: true
    instructions:
        start: |
            Welcome to the Audio Transcribe and Comment application setup!

            This application allows users to upload audio files, transcribe them into text, and add comments to specific sections of the audio.

            During the setup, please provide the following information:

            - **Wispher Model**: Select the transcription model to be used. Available options include 'base' and others you may define.
            - **Admin Password**: Set a strong password for the admin account. Ensure it meets the following criteria:
                - At least 8 characters in length.
                - Contains at least one uppercase letter (A-Z).
                - Contains at least one lowercase letter (a-z).
                - Includes at least one digit (0-9).
                - Includes at least one special character (e.g., @$!%*?&).

            After providing these details, the application will be deployed, and you can access it through the assigned URL.

        end: |
            Congratulations! The Audio Transcribe and Comment application has been successfully deployed.

            You can now access the application at `http://$$cap_appname.$$cap_root_domain`.

            To get started:

            1. **Upload Audio**: Use the upload feature to add your audio files.
            2. **Transcription**: The system will automatically transcribe your audio into text.
            3. **Commenting**: Highlight sections of the transcript and add your comments.

            For more information and updates, visit our [GitHub repository](https://github.com/geo-petrini/audio_transcribe).

            Thank you for using the Audio Transcribe and Comment application!
    displayName: Audio Transcribe
    isOfficial: false
    description: phpMyAdmin is a free software tool written in PHP, intended to handle the administration of MySQL over the Web
    documentation: More documentation can be found on the [GitHub](https://github.com/geo-petrini/audio_transcribe)
